apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: kustomize
  labels:
    app: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: chpinart/fastapi:1.0.0
          ports:
            - containerPort: 5000

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-hpa
  namespace: kustomize
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: kustomize
spec:
  selector:
    app: fastapi
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: kustomize
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - secretName: fastapi-certificate
      hosts:
      - k3seval.chpinart.cloudns.ph
  rules:
  - host: k3seval.chpinart.cloudns.ph
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: fastapi-service
                port:
                  number: 5000