apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: kustomize
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  PGADMIN_DEFAULT_PASSWORD: cm9vdA==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: kustomize
  labels:
    name: pgadmin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: pgadmin
  template:
    metadata:
      labels:
        name: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
          - containerPort: 80
            name: pgadmin
        envFrom:
        - secretRef:
            name: pgadmin-secret

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: kustomize
spec:
  type: NodePort
  selector:
    name: pgadmin
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
    port: 80
    nodePort: 30081