apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgadmin.name }}-secret
  namespace: {{ .Values.namespace }}
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  PGADMIN_DEFAULT_PASSWORD: cm9vdA==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadmin.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.pgadmin.name }}
spec:
  replicas: {{ .Values.pgadmin.replicascount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: {{ .Values.pgadmin.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.pgadmin.name }}
    spec:
      containers:
      - name: {{ .Values.pgadmin.name }}
        image: {{ .Values.pgadmin.image }}
        ports:
          - containerPort: {{ .Values.pgadmin.containerport }}
            name: {{ .Values.pgadmin.name }}
        envFrom:
        - secretRef:
            name: {{ .Values.pgadmin.name }}-secret

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    name: {{ .Values.pgadmin.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.pgadmin.port }}
    targetPort: {{ .Values.pgadmin.targetPort }}
    nodePort: {{ .Values.pgadmin.nodePort }}