apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
   - ../../base

namespace: kustomize

patches:
 - target:
      kind: Deployment
      name: fastapi-deployment
   path: fastapi-patch.yaml